// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fiduciary.Data;

#nullable disable

namespace fiduciary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("fiduciary.Models.KnowledgeArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Title");

                    b.ToTable("KnowledgeArticle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fiduciary",
                            Content = "A fiduciary must act with care, honesty, loyalty, and good faith when managing another person's assets or interests.",
                            Source = "Internal starter note",
                            Summary = "A fiduciary duty is a responsibility to act in another person's best interests.",
                            Tags = "fiduciary,duty,trust,compliance",
                            Title = "What is fiduciary duty?"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Estate Administration",
                            Content = "Deceased estate administration involves identifying assets and liabilities, working with executors, preparing documentation, and distributing the estate according to legal requirements.",
                            Source = "Internal starter note",
                            Summary = "The process of managing and distributing a deceased person's estate.",
                            Tags = "estate,deceased,executor,assets",
                            Title = "What is deceased estate administration?"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Trust Administration",
                            Content = "Trust administration includes managing trustees, beneficiaries, trust assets, documentation, reporting, and compliance obligations.",
                            Source = "Internal starter note",
                            Summary = "The management of a trust according to its deed and applicable law.",
                            Tags = "trust,trustees,beneficiaries,compliance",
                            Title = "What is trust administration?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
